### Categorical Data in Pandas

class_data = {
    "Name" : ["A","B","C","D"],
    "Groups: ["G1',"G2","G3,"G4"]
}

In [6]:
class_data = {
    "Name": ["A", "B", "C", "D"],
    "Groups": ["G1", "G2", "G3", "G4"] # Fixed the quote here
}

In [2]:
import pandas as pd

In [7]:
class_df = pd.DataFrame(class_data)

In [8]:
class_df.head()

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [9]:
class_df["Group_cat"] = pd.Categorical(
    class_df["Groups"],
    categories = ["G3", "G1", "G2", "G4"],
    ordered = True
)

In [10]:
class_df["Group_cat"]

0    G1
1    G2
2    G3
3    G4
Name: Group_cat, dtype: category
Categories (4, str): ['G3' < 'G1' < 'G2' < 'G4']

In [11]:
class_df["Group_cat"] >= "G4"

0    False
1    False
2    False
3     True
Name: Group_cat, dtype: bool

In [12]:
class_df

  Name Groups Group_cat
0    A     G1        G1
1    B     G2        G2
2    C     G3        G3
3    D     G4        G4

In [29]:
titanic_dataset_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_url)

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
df["Embarked"].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [31]:
df["Embarked"] = df["Embarked"].fillna("N")

In [32]:
df["Embarked_Category"] = pd.Categorical(
    df["Embarked"],
    categories= ["N","S","C","Q"],
    ordered = True
)

In [33]:
df["Embarked_Category"].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [34]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,S

In [35]:
df["Sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [36]:
df["sex_custom"] = df["Sex"].astype("category").cat.codes

In [37]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_Category,sex_custom
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,S,1

In [ ]:
df["sex_custom_cat"] = df["Sex"].apply(lambda sex:1 if sex == "male" else 0)

In [41]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_Category,sex_custom,sex_custom_cat
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,S,1,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,S,0,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,S,1,1

In [42]:
df["Sex_replace_custom"] = df["Sex"] = df["Sex"].replace(['female', 'male'], [0, 1])

In [43]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_Category,sex_custom,sex_custom_cat,Sex_replace_custom
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S,S,1,1,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,C,0,0,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S,0,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,S,0,0,0
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S,S,1,1,1

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PassengerId         891 non-null    int64
 1   Survived            891 non-null    int64
 2   Pclass              891 non-null    int64
 3   Name                891 non-null    str
 4   Sex                 891 non-null    object
 5   Age                 714 non-null    float64
 6   SibSp               891 non-null    int64
 7   Parch               891 non-null    int64
 8   Ticket              891 non-null    str
 9   Fare                891 non-null    float64
 10  Cabin               204 non-null    str
 11  Embarked            891 non-null    str
 12  Embarked_Category   891 non-null    category
 13  sex_custom          891 non-null    int8
 14  sex_custom_cat      891 non-null    int64
 15  Sex_replace_custom  891 non-null    object
dtypes: category(1), float64(2), int64(6), int8(1), object(2), str(4)
memory usage: 99.5+ KB

In [48]:
# Raw data dictionary
data = {
    "Event": [
        "Sputnik 1 Launch", 
        "Vostok 1 (Yuri Gagarin)", 
        "Apollo 11 Moon Landing", 
        "Mars Pathfinder Landing", 
        "James Webb Telescope Launch"
    ],
    "Date": [
        "1957-10-04", 
        "1961-04-12", 
        "1969-07-20", 
        "1997-07-04", 
        "2021-12-25"
    ]
}

# Create the DataFrame
df_events = pd.DataFrame(data)

print(df_events)
df_events.info()

                         Event        Date
0             Sputnik 1 Launch  1957-10-04
1      Vostok 1 (Yuri Gagarin)  1961-04-12
2       Apollo 11 Moon Landing  1969-07-20
3      Mars Pathfinder Landing  1997-07-04
4  James Webb Telescope Launch  2021-12-25
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Event   5 non-null      str
 1   Date    5 non-null      str
dtypes: str(2)
memory usage: 212.0 bytes

In [ ]:
# 1. IMPORTANT: Convert the 'Date' column to actual datetime objects
df_events["Date"] = pd.to_datetime(df_events["Date"])

# 2. Extract the Month Name
df_events["Month"] = df_events["Date"].dt.month_name()

# 3. Extract other useful info
df_events["Year"] = df_events["Date"].dt.year
df_events["Day_of_Week"] = df_events["Date"].dt.day_name()

print(df_events)

df_events.info()

                         Event       Date     Month  Year Day_of_Week
0             Sputnik 1 Launch 1957-10-04   October  1957      Friday
1      Vostok 1 (Yuri Gagarin) 1961-04-12     April  1961   Wednesday
2       Apollo 11 Moon Landing 1969-07-20      July  1969      Sunday
3      Mars Pathfinder Landing 1997-07-04      July  1997      Friday
4  James Webb Telescope Launch 2021-12-25  December  2021    Saturday
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Event        5 non-null      str
 1   Date         5 non-null      datetime64[us]
 2   Month        5 non-null      str
 3   Year         5 non-null      int32
 4   Day_of_Week  5 non-null      str
dtypes: datetime64[us](1), int32(1), str(3)
memory usage: 312.0 bytes

In [58]:
df_events["custom_date_category"] = df_events["Date"].astype("category").cat.codes

In [59]:
df_events.head()

,Event,Date,Month,Year,Day_of_Week,custom_date_category
0,Sputnik 1 Launch,1957-10-04,October,1957,Friday,0
1,Vostok 1 (Yuri Gagarin),1961-04-12,April,1961,Wednesday,1
2,Apollo 11 Moon Landing,1969-07-20,July,1969,Sunday,2
3,Mars Pathfinder Landing,1997-07-04,July,1997,Friday,3
4,James Webb Telescope Launch,2021-12-25,December,2021,Saturday,4

…or create a new repository on the command line

echo "# Test" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/azmatrana21/Test.git
git push -u origin main

…or push an existing repository from the command line
git remote add origin https://github.com/azmatrana21/Test.git
git branch -M main
git push -u origin main